var mongoose = require("mongoose"),
  shortid = require("shortid");
var orderSchema = mongoose.Schema({
  oid: { type: Number, unique: true, sparse: true },
  isOnline: { type: Boolean, default: true },
  products: [],
  products1: [
    {
      product_id: String,
      name: String,
      desc: String,
      quantity: Number,
      vou: Number,
      product: String,
      details: String,
      price: Number,
      my_price: Number,
      ctpin: Number,
      isRegistered: { type: Boolean, default: false },
      is2H: { type: Boolean, default: false },
      product_p: { type: Number, default: 0 },
    },
  ],
  tax: Number,
  total_paid: { type: Number, default: 0 },
  discount: { type: Number, default: 0 },
  total: { type: Number, default: 0 },
  date_purchased: { type: String },
  dispatch_date: { type: String },
  tracking_company: String,
  tracking_id: String,
  tracking_link: String,
  order_progress: String,
  status: String,
  paid_struc: {
    cash: Number,
    card: Number,
    bank: Number,
    loaned: Number,
    cashfree: Number,
    ma: Number,
    replace: Number, // New Added
  },
  username: String,
  customer_name: String,
  mobile: Number,
  email: String,
  billName: String,
  add_1: String,
  add_2: String,
  city: String,
  state: String,
  pincode: Number,
  isPaid: { type: Boolean, default: false },
  order_date: { type: Date, default: Date.now },
  billno: Number,
  payment_type: String, //['Card', 'Cash', 'Online', 'Cashfree', 'MA', 'Udhar'] Udhar (New Added) = also loaned if payment_type is Other
  advance: Number,
  customer: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Customer",
  },
  order_note: String,
  isLoan: { type: Boolean, default: false },
  is2H: { type: Boolean, default: false },
  ref2H: String,
  pdf: String,
});

module.exports = mongoose.model("Order", orderSchema);
